# Generated by Django 5.2.7 on 2025-11-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Actor1Name',
            field=models.CharField(max_length=100, verbose_name='Lead Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Actor2Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supporting Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='DirectorName',
            field=models.CharField(max_length=100, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovieGenre',
            field=models.CharField(max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovieTitle',
            field=models.CharField(max_length=200, verbose_name='Movie Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ReleaseYear',
            field=models.PositiveIntegerField(verbose_name='Release Year'),
        ),
    ]
